bytecodealliance/preview2-prototyping

.cargo/config.toml, .github/workflows/main.yml, CODE_OF_CONDUCT.md, COPYRIGHT, Cargo.lock, Cargo.toml, LICENSE-APACHE, LICENSE-Apache-2.0_WITH_LLVM-exception, LICENSE-MIT, ORG_CODE_OF_CONDUCT.md, SECURITY.md, build.rs, src/lib.rs, verify/src/main.rs, wit/wasi-filesystem.wit.md
Implement a polyfill for `path_readlink` in terms of the preview2 `readlink_at` function.
This involves adding a second wasm global, to hold the buffer size.
=> Implement a polyfill for `path_readlink`.

host/src/main.rs, host/src/poll.rs, wit/wasi-poll.wit.md
Per discussion with pchickey, this modifies the poll API to use "futures" rather than a `subscription` type.  The former is arguably closer to the API we'll use once resource support is finalized.
You can create a future by calling `subscribe-read`, `subscribe-write`, `subscribe-wall-clock`, or `subscribe-monotonic-clock` and then poll any number of futures using `poll-oneoff`.  The result is a list of booleans indicating which futures have completed.
In order to determine how many bytes are readable or writable, the application may call `bytes-readable` or `bytes-writable`, respectively, passing the descriptor of interest.
Finally, a future pseudo-handle may be disposed of using `drop-future`, analogous to disposing of a resource handle.
Note that the updated API does not include …
=> convert poll interface to use "future" pseudo-handles

host/src/filesystem.rs, wit/wasi-filesystem.wit.md
Fadvise can apply to regions of files larger than the linear memory address space, so it wants a `filesize` (which is u64) rather than a `size` (which is u32 on wasm32).
=> Change the `len` parameter of `fadvise` to `filesize`.

host/src/filesystem.rs, src/lib.rs, wit/wasi-filesystem.wit.md
See the last commit in https://github.com/WebAssembly/wasi-filesystem/pull/66 for details.
=> Swap `info` and `fd-info`

Cargo.toml, build.rs, src/lib.rs, test-programs/macros/build.rs
I was looking recently to implement args-related syscalls but that would require yet-more globals and yet-more state to be managed. Instead of adding a slew of new globals for this which are all manually kept in sync I opted to instead redesign how global state is managed in the adapter.
The previous multiple `global`s are all removed in favor of just one, as sort of a "tls slot" of sorts. This one remaining slot points to a one-time-allocated `State` object which internally stores information like buffer metadata, fd information, etc. Along the way I've also simplified syscalls with new methods and `?`-using closures.
=> Simplify global state management in adapter

host/tests/runtime.rs, src/lib.rs, test-programs/src/bin/args.rs
This commit updates the implementation of `cabi_export_realloc` to
allocate from a bump-allocated-region in `State` rather than allocating
a separate page for each argument as previously done. Additionally the
argument data is now stored within `State` as well enabling a full
implementation of the `args_get` and `args_sizes_get` syscalls.
=> Implement args_{get,sizes_get} functions

.github/workflows/main.yml, test-programs/macros/build.rs
This updates CI to upload a `wasi_snapshot_preview1.wasm` release artifact from CI. One is stored per CI job in case it needs to be inspected, and additionally a github action is used to maintain a "latest" release for pushes to `main` to ensure that the latest copy of `wasi_snapshot_preview1.wasm` is available.
I haven't thought much about official releases or tags or things like that but figured that this was a good starting place at least.
=> Upload a release artifact from CI

host/src/clocks.rs, host/src/lib.rs, host/src/poll.rs, host/src/tcp.rs, src/lib.rs, wit/wasi.wit
This adds a `poll_oneoff` implementation to src/lib.rs.  It's completely untested.  I was planning on adding a host implementation and using that to test end-to-end, but that raised some tough questions about how much of the existing `wasi-common` scheduler(s) should be reused.  I've decided to focus on other, more widely-used parts of WASI first, but I wanted to share the work I've already done here.
Note that I've modified the return types of a few functions to allow them to return I/O errors.
=> sketch of `poll_oneoff` polyfill

src/lib.rs
When the `command` entrypoint isn't invoked, such as for non-command builds, then prints were not working as they would return `ERRNO_BADF` which is swallowed by at least Rust right now. This instead sets the initialization of `State` to reflect how fd 0 is an empty stdin stream, fd 1 goes to a `log` call, and fd 2 also goes to `log`. During `command` initialization fds 0 and 1 are overwritten with the provided input and for non-command builds this is the state permanently for the program.
It's possible we can add further configuration hooks for this in the future, but this should get at least the initial state of non-command builds more workable.
=> Fix prints in non-command builds

Cargo.lock, host/Cargo.toml, host/src/random.rs
Implements the `wasi_random::WasiRandom::getrandom` method for `WasiCtx` using the [`Standard`] distribution.
If this repo isn't open to PRs, thats fine. I just thought I'd submit a PR as a personal project depends on this, and it would allow me to remove my fork and use this repository directly.
[`Standard`]: https://docs.rs/rand/latest/rand/distributions/index.html#the-standard-distribution
=> Implement `getrandom` using `Standard` distribution

host/src/filesystem.rs, src/lib.rs, wit/wasi.wit
This roughly matches the implementation in `wasi-common` today where it uses the directory entry stream as a form of iterator and the `cookie` represents the `n`th iteration. Not exactly efficient if the `buf` provided to the hostcall is too small to hold many of the entries but there's not a whole lot else that can be done at this time.
This also updates the WIT for `read-dir-entry` to return `option<dir-entry>` instead of `dir-entry` to indicate EOF. I'm not sure if this was an oversight or whether it was intended for an error code to indicate end-of-stream instead, happy to change to either!
=> Implement the `fd_readdir` function

Cargo.lock, host/Cargo.toml, host/src/filesystem.rs, host/src/lib.rs, host/src/tcp.rs
Removes `wit-bindgen-host-wasmtime-rust` and instead uses the `wasmtime::component::bindgen` macro.
This involed a few minor changes to the code, and introduced a `HostResult` type alias in the host.
=> Upgrade `wasmtime` and remove `wit-bindgen-host-wasmtime-rust`

host/src/exit.rs, host/src/lib.rs, host/src/logging.rs, src/lib.rs, wit/wasi.wit
Import wasi-logging twice, once as stdout and once as stderr, and change the host implementation to just pass the string through to the host stdout/stderr as appropriate.
Also, add an API to implement proc_exit with, and implement it.
=> Don't print extra metadata in stdout/stderr, and implement proc_exit

Cargo.lock, host/src/clocks.rs, host/src/random.rs, host/tests/runtime.rs, src/lib.rs, test-programs/Cargo.toml, test-programs/src/bin/random.rs, test-programs/src/bin/stdin.rs, test-programs/src/bin/time.rs, wasi-common/src/clocks.rs, wasi-common/src/pipe.rs
This required fleshing out the `wasi-clocks` host implementation a bit and adding a `read_vectored_at` implementation for `ReadPipe`.
=> add tests for `wasi-random`, `wasi-clocks`, and stdin

host/src/random.rs, src/lib.rs, wit/wasi.wit
This anticipates https://github.com/WebAssembly/wasi-random/pull/18.
=> Add a way to get a random `u64`.

host/src/filesystem.rs, wasi-common/cap-std-sync/src/dir.rs, wasi-common/src/dir.rs
This gets us another step closer to running the Wasmtime tests.
=> Implement host file flags and type functions.

.github/workflows/main.yml
Sometimes it's helpful for people to look at the generated bindings to see how things work; install the wit-bindgen-cli and generate the C and Rust bindings, and upload them.
=> Generate and upload bindings artifacts to make them easier to look at.

host/src/filesystem.rs, host/src/poll.rs, host/tests/runtime.rs, src/lib.rs, test-programs/src/bin/directory_list.rs, test-programs/src/bin/file_read.rs, wasi-common/src/dir.rs, wasi-common/src/table.rs
This adds a `directory_list` test and provides the required host implementation.
I've also added a file length check to the `file_read` test, just to cover a bit more of the API.
=> implement `wasi-filesystem::readdir` and related functions

Cargo.lock, host/src/filesystem.rs, host/src/lib.rs, host/src/poll.rs
This is fix for `wasmtime::component::Error` dropped from https://github.com/bytecodealliance/wasmtime/pull/5397 to keep `host` compiling.
I found https://github.com/bytecodealliance/preview2-prototyping/issues/32 and https://github.com/bytecodealliance/preview2-prototyping/pull/26 talking about this case. PR is outdated and It seems a new design for `HostResult` is comming. 
But now I'm trying to run wasm `component-model` with wasi host bindings. So I think `host` should be compiled correctly.
=> fix compile failed by wasmtime::component::Error dropped

host/src/filesystem.rs
=> update `readdir` etc to use new error handling scheme

host/src/clocks.rs, host/tests/runtime.rs, test-programs/src/bin/default_clocks.rs, wasi-common/src/clocks.rs, wit/wasi.wit
Many users won't need these, because they'll just grab one default clock handle and reuse it for the rest of the program. But it should still be possible to close a clock handle.
Also, add a simple test for the clock APIs.
=> Add `close` functions for clock handles.

Cargo.lock, host/tests/runtime.rs, src/lib.rs, test-programs/src/bin/file_append.rs, wasi-common/cap-std-sync/src/file.rs, wasi-common/src/file.rs
- In the preview1-to-preview2 polyfill, using `append_via_stream`.
- In the host implementation, using a new system-interface `FileIoExt::append` function.
=> Implement file append functionality.

.github/workflows/main.yml, Cargo.lock, host/src/poll.rs, host/tests/runtime.rs, src/lib.rs, test-programs/Cargo.toml, test-programs/macros/build.rs, test-programs/src/bin/poll_stdin.rs, wasi-common/cap-std-sync/src/sched.rs, wasi-common/src/sched.rs, wasi-common/src/sched/subscription.rs
When a `ReadPipe` is reading from a memory buffer, there is no host file descriptor to poll with, but there doesn't need to be because the contents are immediately available. Teach the `poll_oneoff` function to use system-interface's `ReadReady` trait, which returns the number of bytes read to be read immediately, to implement polling for such input sources.
This also fixes the polyfill to avoid calling `bytes_readable` on non-socket handles, which is needed to make the test pass.
=> Teach poll_oneoff how to poll for immediately-available I/O

host/src/filesystem.rs, host/tests/runtime.rs, src/lib.rs, test-programs/src/bin/file_dir_sync.rs, wasi-common/cap-std-sync/src/dir.rs, wasi-common/cap-std-sync/src/file.rs, wasi-common/src/dir.rs, wasi-common/src/file.rs, wasi-common/tokio/src/file.rs
On Windows, there doesn't appear to be a way to sync a directory, to ensure that the directory entry for a file is sync'd. So for now, just silently succeed. I've opened WebAssembly/wasi-filesystem#79 to track this at the spec level.
=> Implement `sync` and `datasync` on files and directories.

Cargo.lock, Cargo.toml, byte-array/Cargo.toml, byte-array/src/lib.rs, src/lib.rs, src/macros.rs
Add a `byte-array` proc-macro crate for converting strings into byte arrays that don't use static initializers, and use it to implement `eprintln`, an `unreachable` that prints the line number, and other macros.
=> Add `eprintln`, `unreachable`, and other macros.

host/src/filesystem.rs, host/tests/runtime.rs, test-programs/macros/src/lib.rs
Filled in trivial (in terms of WasiDir) implementations of the following host filesystem operations:
* `create_directory_at`
* `stat`
* `remove_directory_at`
* `symlink_at`
* `unlink_file_at`
Switch `if true { /* TODO */ return Ok(()) }` short-circuiting logic to use `if EXPECT_FAIL` with a global constant, which makes it easier to run all tests to see which previously failing ones pass.
The following tests now appear to pass:
* `dangling_fd`
* `file_pread_pwrite`
* `file_unbuffered_write`
* `isatty`
* `path_exists`
* `symlink_create`
=> implement some filesystem primitives

test-programs/Cargo.toml, test-programs/src/bin/file_dir_sync.rs, wasi-common/cap-std-sync/src/file.rs
On Windows `sync_all` does `FlushFileBuffers` which fails with an access-denied error if the file not opened for writing. Ignore this error, for compatibility with POSIX-style APIs.
Fixes #66.
=> On Windows, ignore access-denied errors from `sync_all`.

host/src/main.rs, host/tests/runtime.rs, wit/wasi.wit
There will be other worlds in WASI, so rename the `wasi-command` world to accomodate them.
=> Rename the `wasi` world to `wasi-command`.

src/lib.rs, wit/wasi.wit
This commit fixes the non-command build of the WASI adapter by adding a new `wasi.wit` which only has the imports and nothing else.
=> Fix the non-command build

host/src/poll.rs, src/lib.rs, wit/wasi-clocks.wit, wit/wasi-poll.wit, wit/wasi-tcp.wit
You can wait on `waitable`s multiple times, which differs from proper futures, which you can only wait on once.
=> Rename `wasi-future` to `waitable`.

Cargo.lock, src/lib.rs, test-programs/macros/Cargo.toml
This depends on https://github.com/bytecodealliance/wasm-tools/pull/900, which will polyfill an implementation if the main module does not export it.
~~This is a draft for now, since CI will fail until the above PR is merged and the `wit-component` dependency is updated.~~
=> use main module's `cabi_realloc` instead of `memory.grow`

Cargo.lock, host/src/filesystem.rs, host/src/tcp.rs, src/lib.rs, wasi-common/cap-std-sync/src/net.rs, wasi-common/src/connection.rs, wasi-common/src/error.rs, wasi-common/src/lib.rs, wasi-common/src/listener.rs, wasi-common/src/tcp_listener.rs, wasi-common/tokio/src/file.rs, wit/wasi-command.wit, wit/wasi-dns.wit, wit/wasi-filesystem.wit, wit/wasi-ip.wit, wit/wasi-net.wit, wit/wasi-tcp.wit, wit/wasi.wit
Add basic TCP socket APIs.
This is based on @npmccullum's [wasi-snapshot-preview2 draft] which is
in turn based on the [wasi-sockets proposal], though for simplify for
now it omits UDP sockets and some other features.
It's also based on the [pseudo-streams PR]; so that should proceed
first before this.
[draft wasi-snapshot-preview2]: https://github.com/npmccallum/wasi-snapshot-preview2
[wasi-sockets proposal]: https://github.com/WebAssembly/wasi-sockets
[pseudo-streams PR]: https://github.com/bytecodealliance/preview2-prototyping/pull/29
=> Add basic TCP socket APIs.

Cargo.lock, Cargo.toml, test-programs/macros/Cargo.toml, test-programs/macros/build.rs
bump wasm-tools to latest releases
* wit-component includes upstream fixes, plus wasm-metadata
* update wasm-encoder to match
test-programs build.rs: use `cargo +nightly` flag to ensure nightly
on CI, rustup has the default set to nightly, but this may not be the
case on developer machines
=> update wasm-tools, plus minor build fix

wasi-common/cap-std-sync/src/sched.rs
When no timeout is requested, pass `-1` to the host `poll` to disable the timeout.
=> Fix `poll_oneoff`'s timeout value when no timeout is requested.

host/src/filesystem.rs, host/src/io.rs, host/src/lib.rs, host/src/poll.rs, host/src/tcp.rs, host/tests/runtime.rs, src/lib.rs, wasi-common/cap-std-sync/src/lib.rs, wasi-common/cap-std-sync/src/net.rs, wasi-common/cap-std-sync/src/sched.rs, wasi-common/cap-std-sync/src/stdio.rs, wasi-common/src/ctx.rs, wasi-common/src/file.rs, wasi-common/src/lib.rs, wasi-common/src/listener.rs, wasi-common/src/pipe.rs, wasi-common/src/sched.rs, wasi-common/src/sched/subscription.rs, wasi-common/src/stream.rs, wasi-common/src/tcp_listener.rs, wit/wasi-command.wit, wit/wasi-filesystem.wit, wit/wasi-io.wit, wit/wasi-poll.wit, wit/wasi-tcp.wit, wit/wasi.wit
This syncs the prototype's streams with the upstream wasi-io repo.
Streams are unidirectional, so this allows us to statically describe whether something is an input stream or an output stream in an interface.
This differs a little from the component model async streams, which don't have separate input and output streams, but it does partially reflect how the component model async design differentiates between input streams in type signatures, which are passed in as arguments, and output streams, which are returned as return values.
=> Split wasi-stream into separate input and output stream types.

host/tests/runtime.rs, test-programs/wasi-tests/src/bin/directory_seek.rs, test-programs/wasi-tests/src/bin/path_filestat.rs, test-programs/wasi-tests/src/bin/path_link.rs, test-programs/wasi-tests/src/bin/path_open_read_without_rights.rs, test-programs/wasi-tests/src/bin/renumber.rs, test-programs/wasi-tests/src/bin/symlink_filestat.rs, test-programs/wasi-tests/src/bin/truncation_rights.rs, test-programs/wasi-tests/src/config.rs
The readback of the rights fields is broken at the moment and is getting in the way of testing more interesting bits of functionality. We'll re-enable it once other stuff is working.
=> wasi-tests: add configuration to ignore rights readback

host/src/filesystem.rs, host/tests/runtime.rs
This fills in all of the `todo!()` macros hit by the execution of wasi-tests.
I put in a plausible implementation for all but `set_flags`, which requires some design work.
Three additional tests now pass:
* fd_filestat_set
* path_rename_dir_trailing_slashes
* symlink_filestat
And, best of all, since none of the tests panic anymore, I could replace the `EXPECT_FAIL` short-circuit with a function `expect_fail(Result<()>) -> Result<()>`, so we can automatically find out when failing tests start passing.
=> Fill in remaining preview1-based filesystem todos hit by wasi-tests

.github/workflows/main.yml, Cargo.lock, Cargo.toml, build.rs, host/src/main.rs, host/tests/runtime.rs, src/lib.rs, test-programs/macros/Cargo.toml, test-programs/src/bin/export_cabi_realloc.rs
Per https://github.com/bytecodealliance/wasm-tools/pull/919, `wit-component` needs to lazily allocate the adapter stack to avoid premature or infinite reentrance from the main module to the adapter. This means adding an additional `allocation_state` global variable and using it to determine when to return early from an exported function, e.g. because we're in the process of either allocating the stack or allocating `State`.
This requires an updated `wit-component` dependency once https://github.com/bytecodealliance/wasm-tools/pull/919 has been merged.
Fixes #78
=> short-circuit reentrance when allocating stack and `State`

.github/workflows/main.yml, Cargo.lock, Cargo.toml, host/Cargo.toml, src/lib.rs, test-programs/Cargo.toml
* Use precompiled `wit-bindgen` binaries from CI
* Use a release branch of Wasmtime for 6.0.0
* Use `wit-bindgen`-the-crate from crates.io
=> Move to crates.io/releases of dependencies

host/src/env.rs, host/src/filesystem.rs, host/src/lib.rs, host/src/main.rs, host/tests/runtime.rs, src/lib.rs, wasi-common/src/ctx.rs, wit/wasi-command.wit, wit/wasi-environment.wit, wit/wasi-filesystem.wit.md, wit/wasi.wit
Based on #88 
This PR is a step towards making wasi useful outside of the `command` entrypoint.
Instead of providing the environment variables and preopens as arguments to `command`, they are now available via the import functions `wasi-environment::get-environment` and `wasi-filesystem::get-preopens`. Morally, the environment and preopens are import values, but since we don't have import values yet in the component model, instead these functions are specified to always return the same values. When resources are introduced, get-preopens will be callable at most once because it will return an owned descriptor.
The adapter has been changed to lazily fetch the environment and preopens. This is fine for the environment, but laziness is actually a danger for preopens, since they must be …
=> Import functions provide environment variables and preopens

src/lib.rs, wasi-common/cap-std-sync/src/dir.rs
Preview1's `fd_readdir` includes `.` and `..`, but Preview2 is changing to avoid this. Update the Preview2 host implementation to omit these entries, and add code the polyfill to re-add them.
=> Make Preview2's directory iterator omit `.` and `..`.

host/tests/runtime.rs, src/lib.rs, test-programs/src/bin/time.rs
The order of operations for handling the seconds/nanoseconds part of the structure were a bit off which meant that a nonzero nanosecond field would have an unexpected effect on the result.
Closes #92
=> Fix timestamp-to-nanosecond conversion in the adapter

Cargo.lock, host/Cargo.toml
The hope is that Wasmtime from crates.io is, from now on, sufficient to run all the component tests and such.
=> Depend on Wasmtime from crates.io

host/src/filesystem.rs, host/tests/runtime.rs, test-programs/wasi-tests/src/bin/close_preopen.rs, test-programs/wasi-tests/src/bin/overwrite_preopen.rs, wasi-common/cap-std-sync/src/dir.rs, wasi-common/src/ctx.rs, wasi-common/src/dir.rs
This ports the test updates from bytecodealliance/wasmtime#5828 to the preview2-prototype and implements the ability to close preopened file descriptors.
=> Allow preopen file descriptors to be closed.

host/src/filesystem.rs, wasi-common/cap-std-sync/src/file.rs, wasi-common/src/file.rs
Wrap `File`'s contents in an `Arc` so that file handles and stream handles can share the underlying file descriptor, so that we don't have to call `try_clone()`. This avoids the possibility of `try_clone()` failing.
This also makes `File` similar to `Dir`, which already has an `Arc`, in preparation for merging `File` and `Dir` now that WASI has decided that file and directory shouldn't be separate types.
=> Make `read-via-stream` etc. infallible.

.github/workflows/main.yml, Cargo.toml, src/lib.rs, test-programs/macros/build.rs
Naming consistency follow-up on #106
=> drop cli- prefix from reactor, command features & artifact names

.github/workflows/main.yml
This will generate a dummy component for `command`, `proxy` and `reactor` worlds and place them in the release. It will also print the WAT to stdout in GitHub actions.
=> chore: generate dummy component for preview2 worlds

host/src/command.rs, host/src/filesystem.rs, host/tests/command.rs
Based on #115 
This simplifies the various map_err / ok wrapping away, and turns a bunch of what previously trapped into returning the correct error code, so 11 more tests now pass.
=> Use trappable errors in host bindings for wasi-filesystem

host/src/env.rs, host/src/main.rs, host/tests/command.rs, src/lib.rs, wasi-common/cap-std-sync/src/lib.rs, wasi-common/src/ctx.rs, wit/command.wit, wit/environment.wit
This is a follow-on to #123.
Following the principle of wit-ifying preview 1 as faithfully as possible, we are making args available by calling an import function `environment::get-arguments: func() -> list<string>` rather than by passing them to the command's export func `main`.
Implementation in the adapter follows the pattern used for environment variables: arguments are fetched lazily, using the long-lived allocation pool.
This work ended up hitting a rust or wasm-ld behavior/bug which meant I had to (hopefully, temporarily) rename command's `main` to `run`. When the adapter's `main` was modified to take no parameters, something in the toolchain is detecting a special case and renaming it to `__original_main`, and exporting a `main` that takes two i32 parameters. This type signature …
=> Make args available through an import function rather than passed to command main

src/lib.rs
* Pull out some eventtype constant definitions in the poll_oneoff functions, so they are used in both pattern matches
* remove duplicate definition of MAX_DESCRIPTORS, and just rely on size_of::<Descriptors> in src/lib.rs rather than try to calculate size of that struct, which is defined in `mod descriptors` now.
=> Adapter non-functional changes

host/tests/command.rs, src/descriptors.rs
In the adapter, return ERRNO_BADF if trying to close an already closed file. This is the preview 1 behavior, and makes the renumber test pass.
=> Fix wasi renumber test

host/tests/command.rs, src/lib.rs
giving an empty Filestat, instead of returning an error.
This implements the behavior expected by the fd_filestat_get test.
We might end up being able to rename StreamType's Unknown variant to Stdio, since it looks like that is the only place we construct it. However, I will leave that to future work.
=> fix fd_filestat_get: adapter special-case StreamType::Unknown

Cargo.lock, host/Cargo.toml, host/src/main.rs, wasi-common/cap-std-sync/src/lib.rs
Use the latest wasmtime, which needed the following to make the `tracing: true` feature in wasmtime-wit-bindgen actually emit something useful: https://github.com/bytecodealliance/wasmtime/pull/6209
Install the tracing_subscriber in host's main.rs, so that RUST_LOG=host=trace works from the cli. (It already worked in tests, via test_log.)
And finally, implement `--mapdir` as a command line flag, stolen out of the wasmtime cli. I had to rejigger how preopens are constructed slightly to make this work out.
Sample output:
<details>
<pre>
[phickey@pch-tower:src/preview2-prototyping]% RUST_LOG=host=trace cargo run -p host -- read_empty_filename.component.wasm --mapdir /::tmp
Finished dev [unoptimized + debuginfo] target(s) in 0.14s
Running `target/debug/host read_empty_filename.component.wasm …
=> Fix support for tracing, add --mapdir to host cli

host/tests/command.rs, src/lib.rs, test-programs/wasi-tests/src/bin/fd_advise.rs, test-programs/wasi-tests/src/bin/file_allocate.rs, test-programs/wasi-tests/src/config.rs
Adapter always fails with NOTSUP for fd_allocate on files.
Changes to tests are upstream: https://github.com/bytecodealliance/wasmtime/pull/6217
This gets the `file_allocate` and `fd_advise` tests passing.
=> deprecate fd_allocate

host/tests/command.rs, src/lib.rs, test-programs/wasi-tests/src/bin/readlink.rs
* Adapter had an incorrect assertion
* Adapter returned wrong len in the case of truncation
* Test now expects truncation behavior
* Test and truncation behavior changes backported to wasmtime https://github.com/bytecodealliance/wasmtime/pull/6225
=> Fix readlink behavior

host/src/filesystem.rs, src/descriptors.rs, src/lib.rs, test-programs/wasi-tests/src/bin/readlink.rs, wit/deps/filesystem/filesystem.wit
In Preview 2, streams have a pair of blocking and non-blocking methods for reading or writing. Therefore, being blocking or not is no longer a property of the file descriptor, and has been removed from the descriptor-flags. And, as a follow-on, the `set-flags` method was only for changing the nonblocking flag (target operating systems do not support changing any of the other descriptor-flags), so we can drop that method entirely.
For adapting Preview 1, we can store whether a fd is blocking or not as a boolean field in the `File` struct, and still treat it as a preview 1 fdflag. The blocking field in `File` is used to determine whether `fd_read` dispatches to `streams::read` or `streams::blocking_read`. non-Files default to `streams::read`.
The host side of this is not fully implemented: …
=> Eliminate nonblocking from descriptor flags

host/tests/command.rs, src/lib.rs, test-programs/wasi-tests/src/bin/fd_flags_set.rs
This PR fixes two bugs around seek & append behavior:
* the adapter needs to validate to make sure a seek is to a non-negative offset. Fixes `file_seek-tell` test.
* the adapter needs to set or clear the append flag in fd_fdstat_set_flags. Fixes the `fd_flags_set` test.
Plus a little bit of code motion, and commenting the fd_flags_set test better.
=> Fixes for seek/append behavior

host/tests/command.rs, src/lib.rs
There was a special case in poll_oneoff that put in a fake clock stream when a read/write stream for a descriptor wasn't available. The poll_oneoff_files test (in `test_fd_readwrite_invalid_fd()`) checks that poll_oneoff returns a BADF when an invalid fd is subscribed to.
I'm not sure what the special case was patching over, but this passes all of the other tests right now.
cc @sunfishcode, the special case was introduced in https://github.com/bytecodealliance/preview2-prototyping/pull/53 (https://github.com/bytecodealliance/preview2-prototyping/pull/53/commits/53492768b2fbd1999e535a5cb0b1c35d52e6bfc3)
=> adapter poll_oneoff: when descriptors.get_*_stream(fd) fails, die with that error

wasi/Cargo.toml
required to publish to crates.io, with this commit `cargo publish --dry-run` succeeds. also, publish=true is implied, so we can drop that.
=> wasi-preview2-prototype: set crate license to bytecode alliance standard

wasi-common/src/dir.rs, wasi-common/src/file.rs, wasi-common/src/lib.rs, wasi-common/src/preview2/filesystem.rs, wasi-common/src/preview2/io.rs, wasi-common/src/preview2/poll.rs, wasi-common/src/stream.rs, wasi-common/src/table.rs, wasi-sockets/src/network_impl.rs, wasi-sockets/src/tcp.rs
The `wasi-common::Error` enum is actually specific to the filesystem. Table operations (which get used by other crates now) have only three error cases:
* the table is full
* the element is not present
* the element is present with another type
This change makes it possible for these error cases to be translated to whatever error value or trap is appropriate at the use site.
In wasi-common filesystem, I provided the old translation - trap when full, badf otherwise.
In wasi-common streams, we trap when full, and return the empty stream error type otherwise. That type still needs fleshing out in the wit definition.
In wasi-sockets, we always trap, because the error cases there are also not fleshed out, and also trappable errors are broken in sockets (see #163 )
=> wasi-common: Table operations return a distinct TableError enum
